frontend: workaround unused variable warning
$ cd code/cst
$ OSTYPE=linux64 make rel_bin
Create parser cst_parser.c
Compile cst_parser.o
cst_parser.c:2:19: error: 'yysccsid' defined but not used [-Werror=unused-const-variable=]
 static const char yysccsid[] = "@(#)yaccpar 1.9 (Berkeley) 02/21/93";
                   ^~~~~~~~